### ISSUE TITLE
Compilation of project with FastLED fails with compile error since OS version 1.5.0

### ISSUE THREAD

**Issue by happenpappen** [particle-iot/device-os#2077]
<details>
  <summary><i>submission notes</i></summary>

```
**Important:** Please sanitize/remove any confidential info like usernames, passwords, org names, product names/ids, access tokens, client ids/secrets, or anything else you don't wish to share.

Please choose one of the following templates **Bug Report** or **Feature/Enhancement Request** and delete the other.

You may also delete this submission notes header if you'd like. Thank you for contributing!
```
</details>

## Bug Report

A new project which includes FastLED library fails to compile with several compilation errors.

### Expected Behavior

What should it do?

It should compile.

### Observed Behavior

What did it actually do?

Did not compile.

### Steps to Reproduce

How did you make it do that, and which system/user firmware versions were tested?

This is tested with OS version 1.5.0: I created a new, empty project in the WebIDE and just included FastLED (or FastLED2 - errors stay the same) as a library. When verifying the code these errors (and more) are thrown:

../wiring/inc/spark_wiring_spi.h:269:46: ISO C++ forbids declaration of 'instanceSpi' with no type [-fpermissive]
../wiring/inc/spark_wiring_spi.h:269:46: invalid use of dependent type 'typename NSFastLED::SPIOutput<DATA_PIN, CLOCK_PIN, SPI_SPEED>::particle::globals'
../wiring/inc/spark_wiring_spi.h:269:46: ISO C++ forbids declaration of 'instanceSpi' with no type [-fpermissive]
../wiring/inc/spark_wiring_spi.h:269:46: invalid use of '::'

Compiling locally with particle-cli looks the same...

I'm quite sure this just happens since OS version 1.5.0 and worked with 1.4.4.

### Test App

```c
void setup() {

}

void loop() {

}
```

### References

Links to the Community, Docs, Other Issues, etc..

See reports and discussion in: 
https://community.particle.io/t/fastled-library-not-compiling/55663
